backend:
  name: git-gateway
  branch: dev

media_folder: static/assets
public_folder: assets

collections:
  - name: "services"
    label: "Offered Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "service"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Service Name", name: "title", widget: "string"}
      - {label: "Service Image", name: "image", widget: "image"}
      - {label: "Service Description", name: "description", widget: "string"}

  - name: "reviews"
    label: "User Reviews"
    folder: "content/reviews"
    create: true
    slug: "{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "review"}
      - {label: "Author", name: "title", widget: "string"}
      - {label: "Review", name: "review", widget: "string"}

  - name: "homePresentation"
    label: "Home Presentation Slides"
    files: 
      - name: "pres1"
        label: "First Slide"
        file: "content/homeSlides/firstSlide.md"
        fields: 
          - {label: "Text", name: "description", widget: "text"}
          - {label: "Button Link", name: "link", widget: "select", options: ["About Us", "About Us", "About Us"]}
          - {label: "Background Image", name: "image", widget: "image"}
      - name: "pres2"
        label: "Second Slide"
        file: "content/homeSlides/secondSlide.md"
        fields: 
          - {label: "Text", name: "description", widget: "text"}
          - {label: "Button Link", name: "link", widget: "select", options: ["About Us", "About Us", "About Us"]}
          - {label: "Background Image", name: "image", widget: "image"}
      - name: "pres3"
        label: "Third Slide"
        file: "content/homeSlides/thirdSlide.md"
        fields: 
          - {label: "Text", name: "description", widget: "text"}
          - {label: "Button Link", name: "link", widget: "select", options: ["About Us", "About Us", "About Us"]}
          - {label: "Background Image", name: "image", widget: "image"}